language: nix
nix: 2.3.1

sudo: false

cache:
  directories:
  - $HOME/.stack

matrix:
  include:
  - env: STACK_OPTIONS="--resolver nightly-2019-11-20" # GHC 8.8.1
  - env: STACK_OPTIONS="" # GHC 8.6.5
  # - env: STACK_OPTIONS="--resolver lts-13.11" # GHC 8.6.3
  - env: STACK_OPTIONS="--resolver lts-12.26" ALLOW_GOLD_TEST_FAILURES=true # GHC 8.4.4
  # - env: STACK_OPTIONS="--resolver lts-11.22" ALLOW_GOLD_TEST_FAILURES=true # GHC 8.2.2
  # - env: STACK_OPTIONS="--resolver lts-9.21" ALLOW_GOLD_TEST_FAILURES=true # GHC 8.0.2
  # - env: STACK_OPTIONS="--compiler ghc-head" ALLOW_GOLD_TEST_FAILURES=true

  allow_failures:
  - compiler: "ghc-head"

install:
- TEST=${TEST---test}
- ALLOW_GOLD_TEST_FAILURES=${ALLOW_GOLD_TEST_FAILURES-false}
- STACK="stack --nix --no-terminal --skip-ghc-check $STACK_OPTIONS"
- nix-shell --run "$STACK build $TEST --only-dependencies"
- nix-shell --run "$STACK build --only-dependencies"

script:
- nix-shell --run "$STACK build"
- if [ "x$TEST" = "x--test" ]; then nix-shell --run "$STACK build --no-run-tests :misc-examples :graphics-examples"; fi
- if [ "x$TEST" = "x--test" ]; then nix-shell --run "$STACK test :hardware-examples"; fi
- if [ "x$TEST" = "x--test" ]; then nix-shell --run "$STACK build --no-run-tests :gold-tests"; fi
- if [ "x$TEST" = "x--test" ]; then nix-shell --run "$STACK test :gold-tests || $ALLOW_GOLD_TEST_FAILURES"; fi
