nix:
  packages:
    - ghostscript
    - graphviz
    - imagemagick
    - z3

flags: {}
packages:
  - inline
  - known
  - satisfy
  - classes
  - plugin
  - examples
  - graphics
  - hardware
  #- sandbox

extra-deps:
  # Extra packages
  - git: https://github.com/ku-fpg/netlist
    commit: 0f50a9cfd947885cac7fc392a5295cffe0b3ac31
    subdirs:
      - netlist
      - verilog
      - netlist-to-verilog

  - language-glsl-0.3.0@sha256:85c1e7bf2cf5d6e604b7a2899c27e2935033425944db200798e57849e64d4c81,1636

resolver: lts-14.16
